prevent types namespace collision
while trying to run the program without installing it, by simply running:
```
$ python image_bootstrap/__main__.py
```

the following namespace collision issue occurs:
```
$ python image_bootstrap/__main__.py
Traceback (most recent call last):
  File "/home/user/image-bootstrap/image_bootstrap/__main__.py", line 5, in <module>
    import signal
  File "/usr/lib/python3.13/signal.py", line 3, in <module>
    from enum import IntEnum as _IntEnum
  File "/usr/lib/python3.13/enum.py", line 4, in <module>
    from types import MappingProxyType, DynamicClassAttribute
ImportError: cannot import name 'MappingProxyType' from 'types' (consider renaming '/home/user/image-bootstrap/image_bootstrap/types/__init__.py' since it has the same name as the standard library module named 'types' and prevents importing that standard library module)
```

by renaming types to anything except types this issue is prevented and the program can be invoked without issues:
```
$ python image_bootstrap/__main__.py
usage: image-bootstrap [-h] [--version] [--color {never,always,auto}] [--debug] [--quiet] [--verbose]
                       [--arch ARCHITECTURE]
                       [--bootloader {auto,chroot-grub2-device,chroot-grub2-drive,host-extlinux,host-grub2-device,host-grub2-drive,none}]
                       [--bootloader-force] [--hostname NAME] [--openstack] [--password PASSWORD |
                       --password-file FILE] [--resolv-conf FILE] [--disk-id ID] [--first-partition-uuid UUID]
                       [--machine-id ID] [--scripts-pre DIRECTORY] [--scripts-chroot DIRECTORY]
                       [--scripts-post DIRECTORY] [--grub2-install COMMAND] [--cache-dir DIRECTORY]
                       DISTRIBUTION ... DEVICE
image-bootstrap: error: the following arguments are required: DEVICE
```

although this is not the recommended way to run this program as
described in the installation documentation
(https://github.com/hartwork/image-bootstrap?tab=readme-ov-file#Installation),
renaming the types module to something else is a small change that might
save other people some time in the future if they also want to run the
program from `__main__.py` manually.